import React, { useState, useMemo } from 'react';
import {
  View,
  Text,
  TextInput,
  Pressable,
  ScrollView,
  StyleSheet,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import * as Haptics from 'expo-haptics';
import { colors, spacing, borderRadius, typography, neuShadow } from '../src/constants/theme';

type BoardType = 'esp8266' | 'esp32';

function generateSketch(board: BoardType, ssid: string, password: string): string {
  const wifiMode = board === 'esp8266' ? 'WIFI_STA' : 'WIFI_STA';

  return `/**
 * Serial Air — Quick Test Sketch
 * Board: ${board === 'esp8266' ? 'ESP8266' : 'ESP32'}
 * Generated by Serial Air app
 *
 * 1. Paste this into Arduino IDE
 * 2. Select your board: ${board === 'esp8266' ? 'NodeMCU 1.0 / Wemos D1 Mini' : 'ESP32 Dev Module'}
 * 3. Upload
 * 4. Open Serial Air app → device appears automatically
 */

#include <WirelessSerial.h>

const char* ssid = "${ssid}";
const char* password = "${password}";

WirelessSerial ws;
DualPrint* output;

void setup() {
    Serial.begin(115200);
    Serial.println();
    Serial.println("=== Serial Air Test ===");

    // Connect to WiFi
    WiFi.mode(${wifiMode});
    WiFi.begin(ssid, password);

    Serial.print("Connecting to WiFi");
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.println();
    Serial.print("Connected! IP: ");
    Serial.println(WiFi.localIP());

    // Start WirelessSerial
    ws.begin();
    output = ws.mirror(Serial);

    output->println("Serial Air connected!");
    output->print("IP: ");
    output->println(WiFi.localIP());
}

void loop() {
    ws.handle();

    // Send test data every 2 seconds
    output->print("Uptime: ");
    output->print(millis() / 1000);
    output->println("s");

    output->print("Free heap: ");
    output->print(ESP.getFreeHeap());
    output->println(" bytes");

    output->print("WiFi RSSI: ");
    output->print(WiFi.RSSI());
    output->println(" dBm");

    output->print("TCP clients: ");
    output->println(ws.clientCount());

    output->println("---");

    delay(2000);
}
`;
}

export default function CodeGeneratorScreen() {
  const [board, setBoard] = useState<BoardType>('esp8266');
  const [ssid, setSsid] = useState('');
  const [password, setPassword] = useState('');
  const [copied, setCopied] = useState(false);

  const code = useMemo(
    () => generateSketch(board, ssid || 'YOUR_WIFI_SSID', password || 'YOUR_WIFI_PASSWORD'),
    [board, ssid, password]
  );

  const handleCopy = async () => {
    await Clipboard.setStringAsync(code);
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} hitSlop={12}>
          <View style={styles.backButton}>
            <Feather name="arrow-left" size={20} color={colors.text.secondary} />
          </View>
        </Pressable>
        <Text style={styles.headerTitle}>TEST CODE</Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
      >
        {/* Intro */}
        <Text style={styles.introText}>
          Generate a test sketch for your board. Enter your WiFi credentials, copy the code, and paste into Arduino IDE.
        </Text>

        {/* Board Selection */}
        <Text style={styles.sectionLabel}>SELECT BOARD</Text>
        <View style={styles.boardRow}>
          <Pressable
            style={[
              styles.boardButton,
              board === 'esp8266' && styles.boardButtonActive,
            ]}
            onPress={() => setBoard('esp8266')}
          >
            <Feather
              name="cpu"
              size={20}
              color={board === 'esp8266' ? colors.accent.primary : colors.text.muted}
            />
            <Text
              style={[
                styles.boardButtonText,
                board === 'esp8266' && styles.boardButtonTextActive,
              ]}
            >
              ESP8266
            </Text>
          </Pressable>

          <Pressable
            style={[
              styles.boardButton,
              board === 'esp32' && styles.boardButtonActive,
            ]}
            onPress={() => setBoard('esp32')}
          >
            <Feather
              name="cpu"
              size={20}
              color={board === 'esp32' ? colors.accent.primary : colors.text.muted}
            />
            <Text
              style={[
                styles.boardButtonText,
                board === 'esp32' && styles.boardButtonTextActive,
              ]}
            >
              ESP32
            </Text>
          </Pressable>
        </View>

        {/* WiFi Credentials */}
        <Text style={styles.sectionLabel}>WIFI CREDENTIALS</Text>
        <View style={styles.inputCard}>
          <View style={styles.inputRow}>
            <Feather name="wifi" size={18} color={colors.text.muted} style={styles.inputIcon} />
            <TextInput
              style={styles.textInput}
              placeholder="WiFi SSID (network name)"
              placeholderTextColor={colors.text.muted}
              value={ssid}
              onChangeText={setSsid}
              autoCapitalize="none"
              autoCorrect={false}
            />
          </View>
          <View style={styles.divider} />
          <View style={styles.inputRow}>
            <Feather name="lock" size={18} color={colors.text.muted} style={styles.inputIcon} />
            <TextInput
              style={styles.textInput}
              placeholder="WiFi Password"
              placeholderTextColor={colors.text.muted}
              value={password}
              onChangeText={setPassword}
              autoCapitalize="none"
              autoCorrect={false}
              secureTextEntry={false}
            />
          </View>
        </View>

        <View style={styles.infoBox}>
          <Feather name="shield" size={14} color={colors.text.muted} />
          <Text style={styles.infoText}>
            Credentials are only used to generate the sketch. Nothing is stored or sent anywhere.
          </Text>
        </View>

        {/* Code Preview */}
        <Text style={styles.sectionLabel}>GENERATED CODE</Text>
        <View style={styles.codeCard}>
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            style={styles.codeScroll}
          >
            <Text style={styles.codeText}>{code}</Text>
          </ScrollView>
        </View>

        {/* Copy Button */}
        <Pressable style={styles.copyButton} onPress={handleCopy}>
          <Feather
            name={copied ? 'check' : 'clipboard'}
            size={18}
            color={colors.white}
          />
          <Text style={styles.copyButtonText}>
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </Text>
        </Pressable>

        {/* Instructions */}
        <View style={styles.stepsCard}>
          <Text style={styles.stepsTitle}>Next Steps</Text>
          <StepItem number="1" text="Open Arduino IDE" />
          <StepItem number="2" text="Paste the code into a new sketch" />
          <StepItem
            number="3"
            text={`Select board: ${board === 'esp8266' ? 'NodeMCU / Wemos D1 Mini' : 'ESP32 Dev Module'}`}
          />
          <StepItem number="4" text="Click Upload" />
          <StepItem number="5" text="Open Serial Air → device appears automatically" />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function StepItem({ number, text }: { number: string; text: string }) {
  return (
    <View style={styles.stepRow}>
      <View style={styles.stepCircle}>
        <Text style={styles.stepNumber}>{number}</Text>
      </View>
      <Text style={styles.stepText}>{text}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bg.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  headerTitle: {
    ...typography.headerTitle,
    color: colors.text.secondary,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  introText: {
    ...typography.bodySmall,
    color: colors.text.secondary,
    lineHeight: 22,
    marginBottom: spacing.lg,
  },
  sectionLabel: {
    ...typography.sectionHeader,
    color: colors.text.muted,
    marginBottom: spacing.sm,
    marginTop: spacing.md,
  },
  boardRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: spacing.md,
  },
  boardButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.bg.surface,
    borderRadius: borderRadius.innerCard,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
    ...neuShadow.button,
  },
  boardButtonActive: {
    borderColor: colors.accent.glow,
    backgroundColor: colors.bg.surfaceRaised,
  },
  boardButtonText: {
    ...typography.body,
    color: colors.text.muted,
    fontWeight: '600',
  },
  boardButtonTextActive: {
    color: colors.accent.primary,
  },
  inputCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: borderRadius.card,
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...neuShadow.flat,
    marginBottom: spacing.sm,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
  },
  inputIcon: {
    marginRight: 12,
  },
  textInput: {
    flex: 1,
    ...typography.body,
    color: colors.text.primary,
    paddingVertical: 14,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginLeft: spacing.md + 30,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
  },
  infoText: {
    ...typography.caption,
    color: colors.text.muted,
    flex: 1,
    lineHeight: 18,
  },
  codeCard: {
    backgroundColor: colors.bg.input,
    borderRadius: borderRadius.innerCard,
    borderWidth: 1,
    borderColor: colors.border,
    maxHeight: 220,
    marginBottom: spacing.md,
  },
  codeScroll: {
    padding: spacing.md,
  },
  codeText: {
    ...typography.logText,
    color: colors.text.dim,
    lineHeight: 20,
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.accent.primary,
    borderRadius: borderRadius.innerCard,
    paddingVertical: 14,
    marginBottom: spacing.lg,
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  copyButtonText: {
    ...typography.body,
    color: colors.white,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  stepsCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: borderRadius.card,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...neuShadow.flat,
  },
  stepsTitle: {
    ...typography.titleSmall,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.bg.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  stepNumber: {
    ...typography.caption,
    color: colors.accent.primary,
    fontWeight: '700',
  },
  stepText: {
    ...typography.bodySmall,
    color: colors.text.secondary,
    flex: 1,
  },
});
